### ISSUE TITLE
lib incompelete

### ISSUE THREAD

**Issue by Patrick24080735** [killnice/yolov5-D435i#4]
I cant find the position of lib utils.datasets and its missing causes operation failure.Please help me and thanks a lot.

**Comment by killnice** [comment]
你好，首先需要注意你的python运行的目录下是否有同名的utils文件或文件夹，还有你的当前目录层级是否与本项目的目录层级一致

**Comment by Goslng** [comment]
你好，我运行的时候报错了：RuntimeError: No device connected，请问怎么处理

**Comment by Patrick24080735** [comment]
你应该没有连接相机😂



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月14日 09:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [killnice/yolov5-D435i] lib incompelete (Issue #4) |

你好，我运行的时候报错了：RuntimeError: No device connected，请问怎么处理

**Comment by HGS-1998** [comment]
> I cant find the position of lib utils.datasets and its missing causes operation failure.Please help me and thanks a lot.

请问这个问题如何解决？下载的压缩包中包含utils，但为什么from utils.datasets出现错误，自己通过pip install utils 还是不行，请帮助我

**Comment by Patrick24080735** [comment]
我当时也是这个问题，但是util不是一个库，不是用pip安装的，应该是git下载的文件里的，应该是作者没有整理好。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月30日 22:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [killnice/yolov5-D435i] lib incompelete (Issue #4) |

I cant find the position of lib utils.datasets and its missing causes operation failure.Please help me and thanks a lot.

请问这个问题如何解决？下载的压缩包中包含utils，但为什么from utils.datasets出现错误，自己通过pip install utils 还是不行，请帮助我

**Comment by killnice** [comment]
> > I cant find the position of lib utils.datasets and its missing causes operation failure.Please help me and thanks a lot.
> 
> 请问这个问题如何解决？下载的压缩包中包含utils，但为什么from utils.datasets出现错误，自己通过pip install utils 还是不行，请帮助我

你可以试一试从命名行运行代码, 命令行进入到yolov5-D435i目录下, python main_debug.py

**Comment by Lxin23** [comment]
为什么，你运行的文件里边数据集都没有，但是可以识别出东西啊，不应该有一个数据集类嘛，你的main_debug里边也没有用到数据集类啊，是怎么成功识别到东西的啊，不是很懂，请教一下

**Comment by Patrick24080735** [comment]
因为文件里.pt文件内已经包含了一些常规的物体（如人体，遥控器，椅子，手机等），如果你要想识别新的东西比如齿轮这种，需要训练才能达到检测。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月05日 21:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [killnice/yolov5-D435i] lib incompelete (Issue #4) |

为什么，你运行的文件里边数据集都没有，但是可以识别出东西啊，不应该有一个数据集类嘛，你的main_debug里边也没有用到数据集类啊，是怎么成功识别到东西的啊，不是很懂，请教一下

**Comment by Lxin23** [comment]
额，权重文件，我也没看到啊/tt

**Comment by HGS-1998** [comment]
> 额，权重文件，我也没看到啊/tt

非常希望作者可以再次上传一个完整的工程，这将会带给我巨大的帮助，谢谢。

**Comment by killnice** [comment]
> > 额，权重文件，我也没看到啊/tt
> 
> 非常希望作者可以再次上传一个完整的工程，这将会带给我巨大的帮助，谢谢。

github有单个文件上传大小的限制，所以我没有上传权重，请运行weight文件夹下的sh脚本，自动下载权重到本地weight文件夹
